name: flutter_booking_66702168
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0         # เพิ่มการใช้งาน http package
  image_picker: ^1.0.7  # เพิ่มการใช้งาน image_picker package


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true

